# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms 
# will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.

def fib(n)
  current_value = 0
  next_value = 1

  n.times do |i|
    current_value, next_value = next_value, current_value + next_value
  end

  return current_value
end

sum = 0
(1...100).each do |x|
  z = fib(x)
  if z > 4000000
    break
  else
    if z.even?
      sum += z
    end
  end
end

puts sum
