# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

t1 = Time.now 

distinct_terms = {}

(2..100).each do |a|
  (2..100).each do |b|
    distinct_terms[a**b] = 1
  end
end

puts "found #{distinct_terms.keys.length} in #{Time.now - t1}s"

# found 9183 in 0.019303s