# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

# 
# hexagonal numbers are the odd entries of a subset of triangle numbers

def is_pentagonal(p)
  n = ((24 * p + 1)**0.5 + 1) / 6
  n == n.to_i
end

t1 = Time.now
result = 0
i = 143

while true
  i += 1
  result = i * (2 * i - 1)
  break if is_pentagonal(result)
end

puts "found #{result} in #{Time.now - t1}s"
# found 1533776805 in 0.044529s